### ISSUE TITLE
Where.has uses incorrect table alias

### ISSUE THREAD

**Issue by pelletencate** [rzane/baby_squeel#37] opened 2016-11-01 20:21 UTC
When using `joining` to join a table multiple times, baby_squeel doesn't use the correct table aliases if they're being referenced using `where.has`.

For example, in this test case, I have villages, people and cars. People can all have a father. I want to find all people in the village who either own a blue car, or whose father owns a blue car.

This is what I believe should work, but doesn't.

```ruby
require 'bundler/inline'
require 'minitest/spec'
require 'minitest/autorun'

gemfile true do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 5.0.0' # which Active Record version?
  gem 'sqlite3'
  gem 'baby_squeel', github: 'rzane/baby_squeel'
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :villages do |t|
  end

  create_table :people do |t|
    t.integer :village_id
    t.integer :father_id
  end

  create_table :cars do |t|
    t.integer :owner_id
    t.string :color
  end
end

class Village < ActiveRecord::Base
  has_many :people
end

class Person < ActiveRecord::Base
  belongs_to :village
  belongs_to :father, class_name: Person
  has_one :car
end

class Car < ActiveRecord::Base
  belongs_to :person
end


class BabySqueelTest < Minitest::Spec
  it 'works' do
    # Find all people in a village who either have a blue car, or whose fathers have a blue car
    scope = Village.create.people.joining { [
      car.outer,
      father.outer.car.outer
    ]}.where.has {
      (car.color == 'blue') |
      (father.car.color == 'blue')
    }

    scope.to_sql.must_equal %{
      SELECT "people".* FROM "people" LEFT OUTER JOIN "cars" ON "cars"."person_id" = "people"."id" LEFT OUTER JOIN "people" "fathers_people" ON "fathers_people"."id" = "people"."father_id" LEFT OUTER JOIN "cars" "cars_people" ON "cars_people"."person_id" = "fathers_people"."id" WHERE "people"."village_id" = 1 AND ("cars"."color" = 'blue' OR "cars_people"."color" = 'blue')
    }.squish
  end
end
```

**Comment by rzane** [comment] 2016-11-03 19:26
This definitely looks like a bug. I should have some time to investigate further either tomorrow or this weekend.

Thanks for the repro! Much appreciated!

**Comment by mach-kernel** [comment] 2016-11-09 21:34
I have this exact issue. I think @pelletencate's test case is perfect, but just for illustration, here is one of my queries. `postmetas.meta_key` yields `postmetas_wp_posts`.

```ruby
      unscoped
        .joining { postmetas.outer.on(postmetas.post_id == ID) }
        .where.has { (post_type == 'post') & (postmetas.meta_key == 'custom_permalink') }
```

**Comment by pelletencate** [comment] 2016-11-18 17:53
@rzane Any news?

**Comment by rzane** [comment] 2016-11-18 19:26
Sorry for taking so long. I've been very busy, but I definitely have not forgotten about this!

**Comment by rdj** [comment] 2017-01-11 04:59
The original issue makes it sound like the _wrong_ alias is being used, but what I'm seeing is that _no alias_ is being assigned to the joined table. 

Just `LEFT OUTER JOIN t2 ON t2.id = t1.t2_id`, resulting in `Mysql2::Error: Not unique table/alias: 't2'`. 

That's with these versions: 

```
  * activerecord (4.2.7.1)
  * baby_squeel (0.3.1)
```

Ran the test from the OP and seeing the same thing, no aliases at all for the double-joined table:

```
  1) Failure:
BabySqueelTest#test_0001_works [foo.rb:53]:
--- expected
+++ actual
@@ -1 +1 @@
-"SELECT \"people\".* FROM \"people\" LEFT OUTER JOIN \"cars\" ON \"cars\".\"person_id\" = \"people\".\"id\" LEFT OUTER JOIN \"people\" \"fathers_people\" ON \"fathers_people\".\"id\" = \"people\".\"father_id\" LEFT OUTER JOIN \"cars\" \"cars_people\" ON \"cars_people\".\"person_id\" = \"fathers_people\".\"id\" WHERE \"people\".\"village_id\" = 1 AND (\"cars\".\"color\" = 'blue' OR \"cars_people\".\"color\" = 'blue')"
+"SELECT \"people\".* FROM \"people\" LEFT OUTER JOIN \"cars\" ON \"cars\".\"person_id\" = \"people\".\"id\" LEFT OUTER JOIN \"people\" \"fathers_people\" ON \"fathers_people\".\"id\" = \"people\".\"father_id\" LEFT OUTER JOIN \"cars\" ON \"cars\".\"person_id\" = \"fathers_people\".\"id\" WHERE \"people\".\"village_id\" = 1 AND (\"cars\".\"color\" = 'blue' OR \"cars\".\"color\" = 'blue')"
```

**Comment by rdj** [comment] 2017-01-11 21:22
In fact, playing around with this a bit, no matter how I do the join or alias the table, the join condition is using the alias for the cars join rather than the father.cars join. Here's an example, I based this on the OP test case: 

```ruby
require 'bundler/inline'
require 'minitest/spec'
require 'minitest/autorun'

gemfile true do
  source 'https://rubygems.org'
  gem 'activerecord', '4.2.7.1' # which Active Record version?
  gem 'sqlite3'
  gem 'baby_squeel'
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :villages do |t|
  end

  create_table :people do |t|
    t.integer :village_id
    t.integer :father_id
  end

  create_table :cars do |t|
    t.integer :person_id
    t.string :color
  end
end

class Village < ActiveRecord::Base
  has_many :people
end

class Person < ActiveRecord::Base
  belongs_to :village
  belongs_to :father, class_name: Person
  has_one :car, inverse_of: :person
end

class Car < ActiveRecord::Base
  belongs_to :person
end


class BabySqueelTest < Minitest::Spec
  it 'works' do
    # Find all people in a village who either have a blue car, or whose fathers have a blue car
    # .on( father.car.person_id == father.id ).alias('fathers_car')
    scope = Village.create.people.joining{ car.outer }.joining{ father.outer }.joining{ car.outer.alias('fathers_car').on( father.car.person_id == father.id ) }.
      where.has {
      (car.color == 'blue') |
      (father.car.color == 'blue')
    }

    scope.to_sql.must_equal %{
      SELECT "people".* FROM "people" LEFT OUTER JOIN "cars" ON "cars"."person_id" = "people"."id" LEFT OUTER JOIN "people" "fathers_people" ON "fathers_people"."id" = "people"."father_id" LEFT OUTER JOIN "cars" "fathers_car" ON "fathers_car"."person_id" = "fathers_people"."id" WHERE "people"."village_id" = 1 AND ("cars"."color" = 'blue' OR "fathers_car"."color" = 'blue')
    }.squish
  end
end
```

And the result: 

```
  1) Failure:
BabySqueelTest#test_0001_works [foo.rb:54]:
--- expected
+++ actual
@@ -1 +1 @@
-"SELECT \"people\".* FROM \"people\" LEFT OUTER JOIN \"cars\" ON \"cars\".\"person_id\" = \"people\".\"id\" LEFT OUTER JOIN \"people\" \"fathers_people\" ON \"fathers_people\".\"id\" = \"people\".\"father_id\" LEFT OUTER JOIN \"cars\" \"fathers_car\" ON \"fathers_car\".\"person_id\" = \"fathers_people\".\"id\" WHERE \"people\".\"village_id\" = 1 AND (\"cars\".\"color\" = 'blue' OR \"fathers_car\".\"color\" = 'blue')"
+"SELECT \"people\".* FROM \"people\" LEFT OUTER JOIN \"people\" \"fathers_people\" ON \"fathers_people\".\"id\" = \"people\".\"father_id\" LEFT OUTER JOIN \"cars\" \"fathers_car\" ON \"cars\".\"person_id\" = \"fathers_people\".\"id\" LEFT OUTER JOIN \"cars\" ON \"cars\".\"person_id\" = \"people\".\"id\" WHERE \"people\".\"village_id\" = 1 AND (\"cars\".\"color\" = 'blue' OR \"cars\".\"color\" = 'blue')"
```

The most troubling bit being `LEFT OUTER JOIN "cars" "fathers_car" ON "cars"."person_id" = "fathers_people"."id"`, where it uses the alias of the other cars join in this one's join condition. I tried reordering the joins which didn't help either.

**Comment by rdj** [comment] 2017-01-16 17:57
I'm going to apologize for reawakening this thread. I was sick last week and frustrated while trying to migrate to baby_squeel. While I am still having trouble getting this toy example to work properly, my real world example of joining the same table twice with a real database adapter is working properly now that I'm using `baby_squeel 1.0.1` instead of `0.3.1`. I'm not sure why Bundler wanted to use the old version. I am curious why the sqlite toy example isn't working, but maybe it has more to do with the `has_one` relation or something like that which doesn't apply in my real case.

Thanks so much for the work on baby_squeel, now that I can think straight and have the latest gem version, it's going to end up saving me tons of pain. 👍

**Comment by rzane** [comment] 2017-01-16 18:16
Hey @rdj, there's absolutely no need for apology! I appreciate any and all information related to this issue, because I still haven't gotten the chance to look into it. Keep it alive, haha!

And yes, definitely use v1, because it relies on polyamorous to do a lot of the heavy lifting related to joins.

Sorry everybody for being so slow to fix this! 🐢

**Comment by rzane** [comment] 2017-01-31 05:25
Okay, so after some investigation, it is clear that the issue is coming from `BabySqueel::JoinDependency::Finder#find_alias`. It's not always finding the correct JoinAssociation.

In squeel, this alias finding is done here: in https://github.com/activerecord-hackery/squeel/blob/master/lib/squeel/adapters/active_record/4.1/context.rb, so this can be used for reference.

**Closed** 2017-02-03 02:25 UTC
