### ISSUE TITLE
baby_squeel demands fully qualified path

### ISSUE THREAD

**Issue by kbaum** [rzane/baby_squeel#17] opened 2016-07-19 12:24 UTC
Squeel was a bit more layed back when specifying a where condition.  Take the following:

```ruby
Owner.joins{:dogs}.where{ breed = 'mutt' }
```

Squeel is ok with this since breed is only on the dogs table but baby_squeel demands that the query looks like:

```ruby
Owner.joins{:dogs}.where{ dogs.breed = 'mutt' }
```

Not that baby_squeel is incorrect, just makes changing over to baby_squeel a bit more difficult.

**Comment by rzane** [comment] 2016-07-19 14:06
Yeah, this is accurate.

When you say `dogs` within your DSL block, BabySqueel looks for a column named `dogs`. If it doesn't find that, it looks for an association by that name.

So essentially, BabySqueel is doing the following, allowing Arel to do the heavy lifting:

```ruby
dogs_assoc = Owner.reflect_on_association(:dogs)
dogs_assoc.klass.arel_table[:breed].eq('mutt')
```

P.S. I think you want `dogs.breed == 'mutt'`.

**Comment by kbaum** [comment] 2016-07-19 18:31
Makes sense.  In interest of getting adoption from those using squeel, would it make sense to make the behaviour equivalent to squeel?

**Comment by rzane** [comment] 2016-07-20 02:13
I actually just tested out Squeel, and your example would actually do the following:

```ruby
Owner.joins{:dogs}.where{ breed == 'mutt' }
#=> WHERE "owners"."breed" = 'mutt'
```

Are your sure your example was correct?

**Comment by kbaum** [comment] 2016-07-20 09:27
I was going off of code in our project that has been live for a while. I
will try and reproduce and get back to you.

**Comment by rzane** [comment] 2016-07-20 13:34
Thanks! It would also help if you could tell me the Active Record version.

**Comment by kbaum** [comment] 2016-07-21 22:36
Sure! AR 4.2.6 and squeel 1.2.3

**Comment by rzane** [comment] 2016-07-22 03:33
I tried those versions, and I'm still unable to reproduce. Squeel assumes you're querying the `owners` table, and does not verify that `owners.breed` is a valid column.

https://gist.github.com/rzane/377356177290159fc1f9629f27132d75

**Comment by rzane** [comment] 2016-08-02 20:27
Hi @kbaum, I'm going to close this issue. I'm not able to reproduce, plus, I don't intend on supporting this behavior. If you want to query on an association, you have to specify the association name.

**Closed** 2016-08-02 20:27 UTC
