### ISSUE TITLE
Support Arel.star

### ISSUE THREAD

**Issue by rainerborene** [rzane/baby_squeel#83] opened 2017-10-31 19:54 UTC
use case
```ruby
Model.selecting { star & association.data == 'blah' }
```
See here [Arel.star](https://github.com/rails/arel/blob/master/lib/arel.rb#L33-L35)

**Comment by rzane** [comment] 2017-10-31 21:12
Duplicate of https://github.com/rzane/baby_squeel/issues/70

**Closed by rzane** 2017-10-31 21:12 UTC
